name: CI

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nim-version: [stable, devel]
        # Exclude devel on Windows as it is not supported, resulting in:
        # [ERR] 'devel' version and windows runner are not supported yet
        exclude:
          - os: windows-latest
            nim-version: devel
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.nim-version == 'devel' || matrix.os == 'windows-latest' }}
    steps:
      - uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Install libgeos (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgeos-dev

      - name: Install libgeos (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install geos
          echo "LIBRARY_PATH=$(brew --prefix geos)/lib" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=$(brew --prefix geos)/include" >> $GITHUB_ENV

      - name: Setup MSVC command prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install libgeos (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          vcpkg install geos --triplet x64-windows
          $libPath = Join-Path $env:VCPKG_INSTALLATION_ROOT "installed\x64-windows\lib"
          $binPath = Join-Path $env:VCPKG_INSTALLATION_ROOT "installed\x64-windows\bin"
          echo "LIB=$libPath;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "$binPath" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Test
        run: nimble test

      - name: Build documentation
        run: nimble docs
